import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + " bg-[url('/body-bg.png')] min-h-screen"}
      >
        <div className="flex justify-center">
          <main className="bg-white lg:w-8/12 w-11/12 md:mt-8 mt-4 shadow-md">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
